version: '3.8'

services:
  kubecli:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "5787:5000"
    volumes:
      # Mount the Kubernetes config file for accessing clusters
      - ${HOME}/.kube:/root/.kube:ro
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=change-me-in-production
    restart: unless-stopped